# Generated by Django 3.2.15 on 2023-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20230125_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board1', models.TextField(blank=True, null=True)),
                ('board2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
