# Generated by Django 4.0 on 2023-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
