# Generated by Django 4.2 on 2023-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='file5_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
