# Generated by Django 4.0 on 2023-06-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance',
        ),
    ]
